export const MEETER_DAY_SELECTED = 'MEETER_DAY_SELECTED';
export const MEETER_RANGE_UPDATE = 'MEETER_RANGE_UPDATE';
export const MEETER_SEND_BEGIN = 'MEETER_SEND_BEGIN';
export const MEETER_SEND_SUCCESS = 'MEETER_SEND_SUCCESS';
export const MEETER_SEND_FAILURE = 'MEETER_SEND_FAILURE';
export const MEETER_SEND_DISMISS_ERROR = 'MEETER_SEND_DISMISS_ERROR';
